name: Run Generate Scripts

on:
  schedule:
    - cron: '0 */1 * * *' # Runs every 1 hours
  workflow_dispatch:

jobs:
  run-generate-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set time zone
      run: |
        sudo timedatectl set-timezone America/New_York

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml pandas pyyaml

    - name: Run generate_safari_latest.py
      run: python .github/actions/generate_safari_latest.py

    - name: Run generate_firefox_latest.py
      run: python .github/actions/generate_firefox_latest.py

    - name: Run generate_edge_latest.py
      run: python .github/actions/generate_edge_latest.py

    - name: Run generate_chrome_latest.py
      run: python .github/actions/generate_chrome_latest.py

    - name: Run generate_readme.py
      run: python .github/actions/generate_readme.py

    - name: Commit changes
      continue-on-error: true
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Automated update by GitHub Actions" || echo "No changes to commit"
        git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/BOFA.git
